import { type FileContent } from '@/types/project'

export function generateNextProject(content: string): FileContent[] {
  return [
    {
      path: 'app/page.tsx',
      content: content
    },
    {
      path: 'app/layout.tsx',
      content: `
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Preview',
  description: 'Generated by Pagen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`
    },
    {
      path: 'app/globals.css',
      content: `
@tailwind base;
@tailwind components;
@tailwind utilities;`
    }
  ]
}
